[package]
name = "gotham_middleware_diesel"
version = "0.1.0"
authors = ["Shaun Mangelsdorf <s.mangelsdorf@gmail.com>",
           "Bradley Beddoes <bradleybeddoes@gmail.com>"]
description = "A Gotham Middleware that provides access to a Diesel connection via an R2D2 pool to allow other Middleware and Handlers to interact with a database."
license = "MIT/Apache-2.0"
homepage = "https://gotham.rs"
repository = "https://github.com/gotham-rs/middleware-diesel"
readme = "README.md"
categories = ["web-programming::http-server"]
keywords = ["http", "async", "web", "framework", "gotham"]

[dependencies]
log = "0.3.0"
futures = "0.1.0"
gotham = { path = "../gotham" }
gotham_derive = { path = "../gotham/gotham_derive" }

diesel = { version = "0.99.0", features = ["postgres", "sqlite", "mysql"] }
r2d2 = "0.8.1"
r2d2-diesel = "0.99.0"
